### ISSUE TITLE
Allow for the scanning of file content

### ISSUE THREAD

**Issue by ninnymuggins97** [go-enry/go-license-detector#3]
I think it would be useful to allow the user to scan file content directly without having to scan a directory :-). So instead of having to pass a list of directories, you can just provide the file directly.

PR:  [https://github.com/go-enry/go-license-detector/pull/2](url)

**Comment by phanirithvij** [comment]
https://github.com/go-enry/go-license-detector/pull/2

**Comment by bzz** [comment]
Closong as #2 is merged and released under [v4.1.0](https://github.com/go-enry/go-license-detector/releases/tag/v4.1.0).
